In [1]:
pip install numpy

  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 62.4 kB/s eta 0:04:13
   ---------------------------------------- 0.0/15.8 MB 62.4 kB/s eta 0:04:13
   ---------------------------------------- 0.0/15.8 MB 62.4 kB/s eta 0:04:13
   ---------------------------------------- 0.0/15.8 MB 62.4 kB/s

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [12]:
arr =np.random.randint(1,50 ,size=(3,3))

In [13]:
arr

array([[ 9, 30,  9],
       [26, 15,  7],
       [ 1,  7, 46]])

In [16]:
np.size(arr)

9

In [22]:
arr.dtype

dtype('int32')

In [24]:
np.ndim(arr)

2

In [26]:
doarr=np.random.randint(10,100,size=(2,5))

In [27]:
doarr

array([[45, 28, 58, 94, 72],
       [29, 35, 36, 51, 17]])

In [28]:
doarr.shape

(2, 5)

In [5]:
my_arr=np.random.randint(1,50,size=(10))

In [6]:
my_arr

array([15, 20, 10, 29, 45, 36, 27, 19,  6,  7])

In [9]:
np.mean(my_arr)

21.4

In [10]:
arr1=np.random.randint(50,size=(2,3))

In [11]:
arr1

array([[49, 39, 24],
       [36, 43, 23]])

In [12]:
arr2=[[49, 39, 24],
       [36, 43, 23]]


In [13]:
arr2

[[49, 39, 24], [36, 43, 23]]

In [14]:
np.mean(np.add(arr1,arr2))

71.33333333333333

In [15]:
arr3=np.random.randint(1,100,size=(20))

In [16]:
arr3

array([99, 77, 59, 51, 42, 55, 95, 19, 75, 43, 18, 64, 65, 25, 21, 88, 30,
       23,  4, 55])

In [19]:
cond=arr3[arr3>50]

In [20]:
cond

array([99, 77, 59, 51, 55, 95, 75, 64, 65, 88, 55])

In [21]:
arr4=[1,2,3,4,5,6,7,8,9,10]

In [22]:
arr4

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [27]:
np.random.shuffle(arr4)

In [28]:
arr4

[6, 1, 8, 4, 7, 3, 5, 9, 2, 10]